-- Deploy genomes_db:create_v2_lab_tables to pg

-- Purpose: Create empty v2_-prefixed structural copies of the 12 lab workflow tables that
--   import_data.py writes to nightly (sample, tissue, dna_extraction, rna_extraction,
--   hic_lysate, illumina_library, ont_library, pacbio_library, hic_library,
--   rna_library_ilmn, rna_library_kinx, sequencing), so the schema can be extended with
--   newly-discovered spreadsheet columns and data migrated in/validated concurrently,
--   before the live tables are decommissioned.
-- Review source: docs/spreadsheet_column_gap_analysis.md; schema/current_schema.sql and
--   schema/current_constraints.sql baselines (verified against live \d output on
--   2026-08-04).
-- Expected impact: Additive only. Creates 12 new empty tables; does not alter, read from,
--   or write to any existing table. No impact on the nightly import job.
-- Note: populating these tables (updating import_data.py/name_convert.py to write into
--   them, and backfilling history from the live tables) and any future cutover/rename of
--   the live tables to replace them with these is deliberately out of scope here and will
--   be a separate change, mirroring the create_empty_lca_table_copies precedent.

BEGIN;

CREATE TABLE public.v2_sample (
    og_id text NOT NULL,
    field_id text,
    nominal_species_id text,
    common_name text,
    collector text,
    contact text,
    date_collected date,
    sex text,
    weight text,
    lengthtl_and_lengthfl text,
    country text,
    state text,
    location text,
    latitude_collection text,
    longitude_collection text,
    depth_collection text,
    collection_method text,
    preservation_method text,
    sample_condition text,
    photo_voucher text,
    photo_id text,
    specimen_voucher text,
    voucher_id text,
    comments text,
    priority text,
    tissues text,
    extracted text,
    extraction_queue text,
    ilmn text,
    il_status text,
    hifi text,
    pb_status text,
    hic text,
    hic_status text,
    nano text,
    ont_num text,
    rna text,
    rna_status text,
    ilrna text,
    ilrna_status text,
    assigned_species text,
    eschmeyer_id text,
    ncbi_sample_name text,
    ncbi_biosample_id text,
    hifi_lca_outcome text,
    ncbi_id text,
    tol_id text,
    ncbi_bioproject_id_lvl_3_hifi text,
    bioproject_id_haplotype_1 text,
    bioproject_id_haplotype_2 text,
    bioproject_sequencing_data text,
    ncbi_assembly_upload text,
    ncbi_raw_reads_upload text,
    hifi_public text,
    illumina_lca text,
    ncbi_bioproject_id_draft text,
    illumina_public text,
    draft_sra_accessions text,
    draft_assembly_accession text,
    og_num integer GENERATED ALWAYS AS ((SUBSTRING(og_id FROM 3))::integer) STORED,
    project_id text,
    workflow character varying,
    illumina_sequencing text,
    hifi_sequencing text,
    hic_sequencing text,
    nanopore_sequencing text,
    rna_ilmn_sequencing text,
    rna_kinnex_sequencing text,
    rna_extraction text,
    summary_comments character varying,
    embargo_status character varying,
    -- new columns: docs/spreadsheet_column_gap_analysis.md ("sample" gaps)
    sample_condition_upon_preservation text,
    ethics_permit text,
    collection_permit text,
    import_permit text,
    cultural_significance text,
    cites text,
    cms text,
    iucn text,
    epbc text,
    sample_receipt_date date,
    rna_processing_comment text,
    rna_kinnex_status text,
    CONSTRAINT v2_sample_pkey PRIMARY KEY (og_id)
);

CREATE TABLE public.v2_tissue (
    tissue_id text NOT NULL,
    og_id text,
    field_id text,
    alt_id text,
    tissue text,
    extracted integer,
    freezer text,
    shelf integer,
    rack integer,
    level text,
    box text,
    comment text,
    og_num integer GENERATED ALWAYS AS ((SUBSTRING(og_id FROM 3))::integer) STORED,
    -- new column: docs/spreadsheet_column_gap_analysis.md ("tissue" gaps)
    preservation text,
    CONSTRAINT v2_tissue_pkey PRIMARY KEY (tissue_id),
    CONSTRAINT fk_v2_tissue_og_id FOREIGN KEY (og_id) REFERENCES public.v2_sample(og_id)
);

CREATE TABLE public.v2_dna_extraction (
    dna_id text NOT NULL,
    tissue_id text,
    ext_num integer,
    status text,
    extraction_method text,
    extraction_date text,
    extraction_batch_id text,
    final_buffer text,
    volume integer,
    qubit_conc real,
    nano_drop_conc real,
    ratio_260_280 text,
    ratio_260_230 text,
    ratioqubit_nanodrop real,
    total_yield text,
    gdna_femtol_id text,
    av_size text,
    extraction_qc text,
    comment text,
    dna_freezer text,
    dna_shelf integer,
    dna_rack integer,
    dna_level text,
    dna_box text,
    dna_notes text,
    og_num integer GENERATED ALWAYS AS ((regexp_replace(tissue_id, '[^0-9]'::text, ''::text, 'g'::text))::integer) STORED,
    og_id text GENERATED ALWAYS AS (regexp_replace(tissue_id, '^([^0-9]*[0-9]+).*$'::text, '\1'::text)) STORED,
    status_overwrite character varying,
    CONSTRAINT v2_dna_extraction_pkey PRIMARY KEY (dna_id),
    CONSTRAINT fk_v2_dna_extraction_tissue_id FOREIGN KEY (tissue_id) REFERENCES public.v2_tissue(tissue_id)
);

CREATE TABLE public.v2_rna_extraction (
    rna_id text NOT NULL,
    tissue_id text,
    ext_num integer,
    status text,
    extraction_method text,
    extraction_date date,
    extraction_batch_id text,
    final_buffer text,
    volume integer,
    qubit_conc real,
    nano_drop_conc real,
    ratio_260_280 text,
    ratio_260_230 text,
    total_yield integer,
    tapestation_id text,
    rna_dv200 real,
    rin text,
    extraction_qc text,
    comment text,
    rna_freezer text,
    rna_shelf text,
    rna_rack text,
    rna_level text,
    rna_box text,
    rna_notes text,
    og_id text GENERATED ALWAYS AS (regexp_replace(tissue_id, '^([^0-9]*[0-9]+).*$'::text, '\1'::text)) STORED,
    status_overwrite character varying,
    CONSTRAINT v2_rna_extraction_pkey PRIMARY KEY (rna_id),
    CONSTRAINT fk_v2_rna_extraction_tissue_id FOREIGN KEY (tissue_id) REFERENCES public.v2_tissue(tissue_id)
);

CREATE TABLE public.v2_hic_lysate (
    lysate_id text NOT NULL,
    tissue_id text,
    lysate_num integer,
    lysate_status text,
    lysate_prep_date date,
    lysate_batch_id text,
    lysate_conc real,
    total_lysate real,
    lysate_cde real,
    lysate_comments text,
    CONSTRAINT v2_hic_lysate_pkey PRIMARY KEY (lysate_id),
    CONSTRAINT fk_v2_hic_lysate_tissue_id FOREIGN KEY (tissue_id) REFERENCES public.v2_tissue(tissue_id)
);

CREATE TABLE public.v2_illumina_library (
    illumina_library_tube_id text NOT NULL,
    dna_id text,
    ilmn_num integer,
    ilmn_status text,
    library_method text,
    library_date text,
    library_id text,
    index_set text,
    index_well text,
    index_idx text,
    library_qubit_conc text,
    il_comments text,
    status_overwrite character varying,
    og_id text GENERATED ALWAYS AS (regexp_replace(dna_id, '^([^0-9]*[0-9]+).*$'::text, '\1'::text)) STORED,
    CONSTRAINT v2_illumina_library_pkey PRIMARY KEY (illumina_library_tube_id),
    CONSTRAINT fk_v2_illumina_library_dna_id FOREIGN KEY (dna_id) REFERENCES public.v2_dna_extraction(dna_id)
);

CREATE TABLE public.v2_ont_library (
    ont_library_tube_id text NOT NULL,
    dna_id text,
    ont_num integer,
    ont_status text,
    library_date text,
    library_id text,
    library_method text,
    library_type text,
    est_loading_size integer,
    ont_comments text,
    og_id text GENERATED ALWAYS AS (regexp_replace(dna_id, '^([^0-9]*[0-9]+).*$'::text, '\1'::text)) STORED,
    status_overwrite character varying,
    CONSTRAINT v2_ont_library_pkey PRIMARY KEY (ont_library_tube_id),
    CONSTRAINT fk_v2_ont_library_dna_id FOREIGN KEY (dna_id) REFERENCES public.v2_dna_extraction(dna_id)
);

CREATE TABLE public.v2_pacbio_library (
    pacbio_library_tube_id text NOT NULL,
    dna_id text,
    pacb_num integer,
    pacb_status text,
    library_method text,
    library_date text,
    library_id text,
    dna_treatment text,
    index_well text,
    barcode text,
    shear_femtol_id text,
    shear_av_size integer,
    seq_femto_id text,
    seq_av_size real,
    library_conc real,
    comment text,
    status_overwrite character varying,
    og_id text GENERATED ALWAYS AS (regexp_replace(dna_id, '^([^0-9]*[0-9]+).*$'::text, '\1'::text)) STORED,
    CONSTRAINT v2_pacbio_library_pkey PRIMARY KEY (pacbio_library_tube_id),
    CONSTRAINT fk_v2_pacbio_library_dna_id FOREIGN KEY (dna_id) REFERENCES public.v2_dna_extraction(dna_id)
);

CREATE TABLE public.v2_hic_library (
    hic_library_tube_id text NOT NULL,
    lysate_id text,
    hic_num integer,
    hic_status text,
    library_method text,
    library_date text,
    library_id text,
    prox_ligation_conc real,
    purified_dna_total real,
    index_set text,
    library_conc real,
    library_size integer,
    hic_comments text,
    status_overwrite character varying,
    og_id text GENERATED ALWAYS AS (regexp_replace(lysate_id, '^([^0-9]*[0-9]+).*$'::text, '\1'::text)) STORED,
    -- new columns: docs/spreadsheet_column_gap_analysis.md ("hic_library" gaps)
    processing_notes text,
    index_i5 text,
    index_i7 text,
    library_yield real,
    pcr_dup_read_pairs real,
    nodup_cis_read_pairs_1kb real,
    expected_distinct_30m_reads bigint,
    CONSTRAINT v2_hic_library_pkey PRIMARY KEY (hic_library_tube_id),
    CONSTRAINT fk_v2_hic_library_lysate_id FOREIGN KEY (lysate_id) REFERENCES public.v2_hic_lysate(lysate_id)
);

CREATE TABLE public.v2_rna_library_ilmn (
    rna_library_tube_id text NOT NULL,
    rna_id text,
    rna_num integer,
    rna_status text,
    library_method text,
    library_date text,
    library_id text,
    library_size integer,
    perc_product real,
    library_qubit_conc real,
    library_molarity text,
    index_set text,
    index_well text,
    index_inx text,
    kinnex_primers text,
    kinnex_barcode text,
    comments text,
    og_id text GENERATED ALWAYS AS (regexp_replace(rna_id, '^([^0-9]*[0-9]+).*$'::text, '\1'::text)) STORED,
    status_overwrite character varying,
    CONSTRAINT v2_rna_library_ilmn_pkey PRIMARY KEY (rna_library_tube_id),
    CONSTRAINT fk_v2_rna_library_ilmn_rna_id FOREIGN KEY (rna_id) REFERENCES public.v2_rna_extraction(rna_id)
);

-- No FK on rna_id here, matching the live rna_library_kinx table today (see
-- docs/data_dictionary.md: "Add FK to rna_extraction after validation" — not yet done live).
CREATE TABLE public.v2_rna_library_kinx (
    rna_library_tube_id character varying(50) NOT NULL,
    rna_id character varying(50),
    rna_num integer,
    rna_status character varying(50),
    library_method character varying(100),
    processing_comment text,
    synthesis_date date,
    part1_batch_id character varying(50),
    synthesis_conc real,
    part2_batch_id character varying(50),
    final_qubit_conc real,
    library_size integer,
    kinnex_primers character varying(20),
    kinnex_barcode character varying(20),
    pool_id character varying(50),
    plate integer,
    plate_location character varying(5),
    comments text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    og_id text GENERATED ALWAYS AS (regexp_replace((rna_id)::text, '^([^0-9]*[0-9]+).*$'::text, '\1'::text)) STORED,
    status_overwrite character varying,
    CONSTRAINT v2_rna_library_kinx_pkey PRIMARY KEY (rna_library_tube_id)
);

CREATE TABLE public.v2_sequencing (
    sequencing_id text NOT NULL,
    og_id text GENERATED ALWAYS AS ("substring"(sequencing_id, '([A-Z]{2}[0-9]+)'::text)) STORED,
    rna_library_tube_id text,
    illumina_library_tube_id text,
    ont_library_tube_id text,
    pacbio_library_tube_id text,
    hic_library_tube_id text,
    technology text,
    instrument text,
    run_date text,
    run_id text,
    seq_date text GENERATED ALWAYS AS (split_part(run_id, '_'::text, 2)) STORED,
    cell_id text,
    smrt_num integer,
    seq_comments text,
    seq_type text,
    design_no integer,
    og_num integer GENERATED ALWAYS AS (("substring"(sequencing_id, '^OG([0-9]+)'::text))::integer) STORED,
    -- new column: docs/spreadsheet_column_gap_analysis.md ("sequencing" gaps)
    hic_depth text,
    CONSTRAINT v2_sequencing_pkey PRIMARY KEY (sequencing_id),
    CONSTRAINT fk_v2_sequencing_hic_library FOREIGN KEY (hic_library_tube_id) REFERENCES public.v2_hic_library(hic_library_tube_id),
    CONSTRAINT fk_v2_sequencing_illumina_library FOREIGN KEY (illumina_library_tube_id) REFERENCES public.v2_illumina_library(illumina_library_tube_id),
    CONSTRAINT fk_v2_sequencing_ont_library FOREIGN KEY (ont_library_tube_id) REFERENCES public.v2_ont_library(ont_library_tube_id),
    CONSTRAINT fk_v2_sequencing_pacbio_library FOREIGN KEY (pacbio_library_tube_id) REFERENCES public.v2_pacbio_library(pacbio_library_tube_id)
);

COMMIT;
