ALTER TABLE public.blast_filtered_lca ADD CONSTRAINT blast_filtered_lca_new_pk PRIMARY KEY (og_id, tech, seq_date, code, annotation, match_sequence_id, region);
ALTER TABLE public."blast_filtered_lca_SS260818" ADD CONSTRAINT blast_filtered_lca_pk PRIMARY KEY (og_id, tech, seq_date, code, annotation, match_sequence_id, region);
ALTER TABLE public.data_package_artifact ADD CONSTRAINT data_package_artifact_component_id_fkey FOREIGN KEY (component_id) REFERENCES data_package_component(id) ON DELETE CASCADE;
ALTER TABLE public.data_package_artifact ADD CONSTRAINT data_package_artifact_delivery_id_component_id_artifact_typ_key UNIQUE (delivery_id, component_id, artifact_type, batch_number, filename);
ALTER TABLE public.data_package_artifact ADD CONSTRAINT data_package_artifact_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES data_package_delivery(id) ON DELETE CASCADE;
ALTER TABLE public.data_package_artifact ADD CONSTRAINT data_package_artifact_pkey PRIMARY KEY (id);
ALTER TABLE public.data_package_artifact ADD CONSTRAINT data_package_artifact_size_bytes_check CHECK (size_bytes >= 0);
ALTER TABLE public.data_package_component ADD CONSTRAINT data_package_component_check CHECK (NOT override_used OR NULLIF(btrim(override_reason), ''::text) IS NOT NULL);
ALTER TABLE public.data_package_component ADD CONSTRAINT data_package_component_component_type_check CHECK (component_type = ANY (ARRAY['reference'::text, 'draft'::text, 'mito'::text]));
ALTER TABLE public.data_package_component ADD CONSTRAINT data_package_component_delivery_id_component_type_key UNIQUE (delivery_id, component_type);
ALTER TABLE public.data_package_component ADD CONSTRAINT data_package_component_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES data_package_delivery(id) ON DELETE CASCADE;
ALTER TABLE public.data_package_component ADD CONSTRAINT data_package_component_pkey PRIMARY KEY (id);
ALTER TABLE public.data_package_delivery ADD CONSTRAINT data_package_delivery_archive_count_check CHECK (archive_count >= 0);
ALTER TABLE public.data_package_delivery ADD CONSTRAINT data_package_delivery_delivery_version_check CHECK (delivery_version > 0);
ALTER TABLE public.data_package_delivery ADD CONSTRAINT data_package_delivery_pkey PRIMARY KEY (id);
ALTER TABLE public.data_package_delivery ADD CONSTRAINT data_package_delivery_project_id_check CHECK (project_id ~ '^OGP[0-9]+'::text);
ALTER TABLE public.data_package_delivery ADD CONSTRAINT data_package_delivery_project_id_delivery_version_key UNIQUE (project_id, delivery_version);
ALTER TABLE public.data_package_delivery ADD CONSTRAINT data_package_delivery_run_id_key UNIQUE (run_id);
ALTER TABLE public.data_package_delivery ADD CONSTRAINT data_package_delivery_total_bytes_check CHECK (total_bytes >= 0);
ALTER TABLE public.data_package_email ADD CONSTRAINT data_package_email_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES data_package_delivery(id) ON DELETE CASCADE;
ALTER TABLE public.data_package_email ADD CONSTRAINT data_package_email_link_set_id_fkey FOREIGN KEY (link_set_id) REFERENCES data_package_link_set(id);
ALTER TABLE public.data_package_email ADD CONSTRAINT data_package_email_pkey PRIMARY KEY (id);
ALTER TABLE public.data_package_email ADD CONSTRAINT data_package_email_preview_id_key UNIQUE (preview_id);
ALTER TABLE public.data_package_email_recipient ADD CONSTRAINT data_package_email_recipient_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES project_delivery_contact(id);
ALTER TABLE public.data_package_email_recipient ADD CONSTRAINT data_package_email_recipient_email_id_fkey FOREIGN KEY (email_id) REFERENCES data_package_email(id) ON DELETE CASCADE;
ALTER TABLE public.data_package_email_recipient ADD CONSTRAINT data_package_email_recipient_email_id_recipient_role_email_key UNIQUE (email_id, recipient_role, email);
ALTER TABLE public.data_package_email_recipient ADD CONSTRAINT data_package_email_recipient_pkey PRIMARY KEY (id);
ALTER TABLE public.data_package_email_recipient ADD CONSTRAINT data_package_email_recipient_recipient_role_check CHECK (recipient_role = ANY (ARRAY['to'::text, 'cc'::text, 'bcc'::text]));
ALTER TABLE public.data_package_item ADD CONSTRAINT data_package_item_component_id_fkey FOREIGN KEY (component_id) REFERENCES data_package_component(id) ON DELETE CASCADE;
ALTER TABLE public.data_package_item ADD CONSTRAINT data_package_item_component_id_og_id_seq_id_key UNIQUE (component_id, og_id, seq_id);
ALTER TABLE public.data_package_item ADD CONSTRAINT data_package_item_disposition_check CHECK (disposition = ANY (ARRAY['included'::text, 'excluded'::text, 'pending'::text]));
ALTER TABLE public.data_package_item ADD CONSTRAINT data_package_item_pkey PRIMARY KEY (id);
ALTER TABLE public.data_package_link_set ADD CONSTRAINT data_package_link_set_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES data_package_delivery(id) ON DELETE CASCADE;
ALTER TABLE public.data_package_link_set ADD CONSTRAINT data_package_link_set_pkey PRIMARY KEY (id);
ALTER TABLE public.data_package_link_set ADD CONSTRAINT data_package_link_set_previous_link_set_id_fkey FOREIGN KEY (previous_link_set_id) REFERENCES data_package_link_set(id);
ALTER TABLE public.design_description ADD CONSTRAINT design_description_pk PRIMARY KEY (design_no);
ALTER TABLE public.dna_extraction ADD CONSTRAINT "DNA_Extraction_pkey" PRIMARY KEY (dna_id);
ALTER TABLE public.dna_extraction ADD CONSTRAINT fk_tissue_id FOREIGN KEY (tissue_id) REFERENCES tissue(tissue_id);
ALTER TABLE public.draft_genomes ADD CONSTRAINT draft_genomes_pkey PRIMARY KEY (og_id, seq_date);
ALTER TABLE public.ena_related_assemblies ADD CONSTRAINT ena_related_archive_check CHECK (archive = ANY (ARRAY['ENA'::text, 'NCBI'::text, 'OTHER'::text]));
ALTER TABLE public.ena_related_assemblies ADD CONSTRAINT ena_related_assemblies_og_id_fkey FOREIGN KEY (og_id) REFERENCES ena_specimen_accessions(og_id);
ALTER TABLE public.ena_related_assemblies ADD CONSTRAINT ena_related_assemblies_og_id_relationship_type_archive_acce_key UNIQUE (og_id, relationship_type, archive, accession);
ALTER TABLE public.ena_related_assemblies ADD CONSTRAINT ena_related_assemblies_pkey PRIMARY KEY (id);
ALTER TABLE public.ena_related_assemblies ADD CONSTRAINT ena_related_relationship_check CHECK (relationship_type = ANY (ARRAY['reference'::text, 'draft'::text]));
ALTER TABLE public.ena_specimen_accessions ADD CONSTRAINT ena_specimen_accessions_ena_biosample_accession_key UNIQUE (ena_biosample_accession);
ALTER TABLE public.ena_specimen_accessions ADD CONSTRAINT ena_specimen_accessions_og_numeric_key UNIQUE (og_numeric);
ALTER TABLE public.ena_specimen_accessions ADD CONSTRAINT ena_specimen_accessions_pkey PRIMARY KEY (og_id);
ALTER TABLE public.ena_specimen_accessions ADD CONSTRAINT ena_specimen_biosample_check CHECK (ena_biosample_accession IS NULL OR ena_biosample_accession ~ '^SAM(EA|N|D)[0-9]+$'::text);
ALTER TABLE public.ena_specimen_accessions ADD CONSTRAINT ena_specimen_og_id_check CHECK (og_id ~ '^OG[0-9]+$'::text);
ALTER TABLE public.ena_specimen_accessions ADD CONSTRAINT ena_specimen_og_numeric_check CHECK (og_numeric >= 0 AND og_numeric <= 999999);
ALTER TABLE public.ena_specimen_accessions ADD CONSTRAINT ena_specimen_og_numeric_matches_check CHECK (og_numeric = SUBSTRING(og_id FROM 3)::integer);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_accession_presence_check CHECK (submission_status <> 'ACCESSION_ASSIGNED'::text OR ena_analysis_accession IS NOT NULL);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_analysis_accession_check CHECK (ena_analysis_accession IS NULL OR ena_analysis_accession ~ '^ERZ[0-9]+$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_assembly_accession_check CHECK (ena_assembly_accession IS NULL OR ena_assembly_accession ~ '^GCA_[0-9]{9}[.][0-9]+$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_biosample_check CHECK (biosample_accession IS NULL OR biosample_accession ~ '^SAM(EA|N|D)[0-9]+$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_failure_reason_check CHECK (submission_status <> 'FAILED'::text OR error_message IS NOT NULL);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_full_seqid_check CHECK (full_seqid ~ '^OG[0-9]+[.][A-Za-z0-9._-]+$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_locus_tag_prefix_check CHECK (locus_tag_prefix IS NULL OR locus_tag_prefix ~ '^[A-Z][A-Z0-9]{2,11}$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_pkey PRIMARY KEY (full_seqid, webin_mode);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_receipt_digest_check CHECK (receipt_sha256 IS NULL OR receipt_sha256 ~ '^[0-9a-f]{64}$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_run_accessions_check CHECK (run_accessions IS NULL OR array_to_string(run_accessions, ' '::text) ~ '^((ERR|SRR|DRR)[0-9]+( |$))*$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_sample_accession_check CHECK (ena_sample_accession IS NULL OR ena_sample_accession ~ '^ERS[0-9]+$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_sequence_accession_check CHECK (ena_sequence_accession IS NULL OR ena_sequence_accession ~ '^[A-Z]{2}[0-9]{6,8}([.][0-9]+)?$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_status_check CHECK (submission_status = ANY (ARRAY['NOT_SUBMITTED'::text, 'SUBMITTED'::text, 'ACCESSION_ASSIGNED'::text, 'FAILED'::text]));
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_study_accession_check CHECK (ena_study_accession IS NULL OR ena_study_accession ~ '^PRJEB[0-9]+$'::text);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_submitted_at_check CHECK ((submission_status <> ALL (ARRAY['SUBMITTED'::text, 'ACCESSION_ASSIGNED'::text])) OR submitted_at IS NOT NULL);
ALTER TABLE public.ena_submissions ADD CONSTRAINT ena_submissions_webin_mode_check CHECK (webin_mode = ANY (ARRAY['production'::text, 'test'::text]));
ALTER TABLE public.ena_validation_attempts ADD CONSTRAINT ena_validation_attempts_pkey PRIMARY KEY (id);
ALTER TABLE public.ena_validation_attempts ADD CONSTRAINT ena_validation_submission_ready_check CHECK (NOT submission_ready OR webin_status = 'PASS'::text);
ALTER TABLE public.hic_library ADD CONSTRAINT "HiC_Library_pkey" PRIMARY KEY (hic_library_tube_id);
ALTER TABLE public.hic_library ADD CONSTRAINT fk_lysate_id FOREIGN KEY (lysate_id) REFERENCES hic_lysate(lysate_id);
ALTER TABLE public.hic_lysate ADD CONSTRAINT "HiC_Lysate_pkey" PRIMARY KEY (lysate_id);
ALTER TABLE public.hic_lysate ADD CONSTRAINT fk_tissue_id FOREIGN KEY (tissue_id) REFERENCES tissue(tissue_id);
ALTER TABLE public.hic_reads_qc ADD CONSTRAINT hic_reads_qc_pkey PRIMARY KEY (og_id, tissue, ext_type, lib_code, lane, run_id);
ALTER TABLE public.hifi_reads_qc ADD CONSTRAINT hifi_reads_qc_pkey PRIMARY KEY (og_id, tissue, ext_type, lib_code, run_id);
ALTER TABLE public.illumina_library ADD CONSTRAINT "Illumina_Library_pkey" PRIMARY KEY (illumina_library_tube_id);
ALTER TABLE public.illumina_library ADD CONSTRAINT fk_dna_id FOREIGN KEY (dna_id) REFERENCES dna_extraction(dna_id);
ALTER TABLE public.lca ADD CONSTRAINT fk_mitogenome_lca FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES mitogenome_data(og_id, tech, seq_date, code);
ALTER TABLE public.lca ADD CONSTRAINT lca_content_unique UNIQUE (og_id, tech, seq_date, code, annotation, region, content_hash);
ALTER TABLE public."lca_SS260818" ADD CONSTRAINT fk_mitogenome FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES "mitogenome_data_SS260818"(og_id, tech, seq_date, code);
ALTER TABLE public."lca_SS260818" ADD CONSTRAINT lca_results_unique UNIQUE (og_id, tech, seq_date, code, annotation, region, lca_run_date);
ALTER TABLE public.lca_old ADD CONSTRAINT fk_mitogenome FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES "mitogenome_data_SS260818"(og_id, tech, seq_date, code);
ALTER TABLE public.lca_old ADD CONSTRAINT lca_unique UNIQUE (og_id, tech, seq_date, code, annotation, region, lca_run_date);
ALTER TABLE public.lca_raw_results ADD CONSTRAINT fk_mitogenome_lca_raw_results FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES mitogenome_data(og_id, tech, seq_date, code);
ALTER TABLE public.lca_raw_results ADD CONSTRAINT lca_raw_results_content_unique UNIQUE (og_id, tech, seq_date, code, annotation, sequence_region, accession_id, content_hash);
ALTER TABLE public."lca_raw_results_SS260818" ADD CONSTRAINT fk_mitogenome FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES "mitogenome_data_SS260818"(og_id, tech, seq_date, code);
ALTER TABLE public."lca_raw_results_SS260818" ADD CONSTRAINT lca_raw_results_unique UNIQUE (og_id, tech, seq_date, code, annotation, sequence_region, lca_run_date, accession_id);
ALTER TABLE public.lca_validation ADD CONSTRAINT fk_mitogenome_lca_validation FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES mitogenome_data(og_id, tech, seq_date, code);
ALTER TABLE public.lca_validation ADD CONSTRAINT lca_validation_new_pk PRIMARY KEY (og_id, tech, seq_date, code, annotation);
ALTER TABLE public."lca_validation_SS260818" ADD CONSTRAINT lca_validation_mitogenome_data_fk FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES "mitogenome_data_SS260818"(og_id, tech, seq_date, code);
ALTER TABLE public."lca_validation_SS260818" ADD CONSTRAINT lca_validation_pk PRIMARY KEY (og_id, tech, seq_date, code, annotation);
ALTER TABLE public.master_species ADD CONSTRAINT master_species_pkey PRIMARY KEY (species);
ALTER TABLE public.master_species_genome ADD CONSTRAINT fk_master_species_genome_species FOREIGN KEY (species) REFERENCES master_species(species) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.master_species_genome ADD CONSTRAINT master_species_genome_pkey PRIMARY KEY (species);
ALTER TABLE public.mitogenome_data ADD CONSTRAINT mitogenome_data_pkey_1 PRIMARY KEY (og_id, tech, seq_date, code);
ALTER TABLE public.mitogenome_data ADD CONSTRAINT mitogenome_data_unique_1 UNIQUE (og_id, tech, seq_date, code, annotation);
ALTER TABLE public."mitogenome_data_SS260818" ADD CONSTRAINT mitogenome_data_pkey PRIMARY KEY (og_id, tech, seq_date, code);
ALTER TABLE public."mitogenome_data_SS260818" ADD CONSTRAINT mitogenome_data_unique UNIQUE (og_id, tech, seq_date, code, annotation);
ALTER TABLE public.ncbi_genome_assemblies ADD CONSTRAINT ncbi_genome_assemblies_assembly_accession_key UNIQUE (assembly_accession);
ALTER TABLE public.ont_library ADD CONSTRAINT "ONT_Library_pkey" PRIMARY KEY (ont_library_tube_id);
ALTER TABLE public.ont_library ADD CONSTRAINT fk_dna_id FOREIGN KEY (dna_id) REFERENCES dna_extraction(dna_id);
ALTER TABLE public.pacbio_library ADD CONSTRAINT "PacBio_Library_pkey" PRIMARY KEY (pacbio_library_tube_id);
ALTER TABLE public.pacbio_library ADD CONSTRAINT fk_dna_id FOREIGN KEY (dna_id) REFERENCES dna_extraction(dna_id);
ALTER TABLE public.project_delivery_contact ADD CONSTRAINT project_delivery_contact_pkey PRIMARY KEY (id);
ALTER TABLE public.project_delivery_contact ADD CONSTRAINT project_delivery_contact_project_id_email_recipient_role_key UNIQUE (project_id, email, recipient_role);
ALTER TABLE public.project_delivery_contact ADD CONSTRAINT project_delivery_contact_recipient_role_check CHECK (recipient_role = ANY (ARRAY['to'::text, 'cc'::text, 'bcc'::text]));
ALTER TABLE public.raw_data ADD CONSTRAINT raw_data_pkey PRIMARY KEY (run_id, lane_id, filename);
ALTER TABLE public.raw_qc ADD CONSTRAINT raw_qc_pkey PRIMARY KEY (og_id);
ALTER TABLE public.ref_genomes ADD CONSTRAINT ref_genomes_pkey PRIMARY KEY (og_id, seq_date, stage, haplotype, version);
ALTER TABLE public.ref_genomes_assembly_uploads ADD CONSTRAINT ref_genomes_uploads_pkey PRIMARY KEY (og_id);
ALTER TABLE public.ref_genomes_sra_uploads ADD CONSTRAINT ref_genomes_sra_runs_og_id_fkey FOREIGN KEY (og_id) REFERENCES ref_genomes_assembly_uploads(og_id);
ALTER TABLE public.ref_genomes_sra_uploads ADD CONSTRAINT ref_genomes_sra_runs_pkey PRIMARY KEY (srr_accession);
ALTER TABLE public.rna_extraction ADD CONSTRAINT "RNA_Extraction_pkey" PRIMARY KEY (rna_id);
ALTER TABLE public.rna_extraction ADD CONSTRAINT fk_tissue_id FOREIGN KEY (tissue_id) REFERENCES tissue(tissue_id);
ALTER TABLE public.rna_library_ilmn ADD CONSTRAINT "RNA_Library_pkey" PRIMARY KEY (rna_library_tube_id);
ALTER TABLE public.rna_library_ilmn ADD CONSTRAINT fk_rna_id FOREIGN KEY (rna_id) REFERENCES rna_extraction(rna_id);
ALTER TABLE public.rna_library_kinx ADD CONSTRAINT rna_library_kinx_pkey PRIMARY KEY (rna_library_tube_id);
ALTER TABLE public.rna_qc_kinnex ADD CONSTRAINT rna_qc_run_id_tube_uniq UNIQUE (run_id, rna_tube_id);
ALTER TABLE public.sample ADD CONSTRAINT "Sample_pkey" PRIMARY KEY (og_id);
ALTER TABLE public.schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);
ALTER TABLE public.sequencing ADD CONSTRAINT "Sequencing_pkey" PRIMARY KEY (sequencing_id);
ALTER TABLE public.sequencing ADD CONSTRAINT fk_hic_library FOREIGN KEY (hic_library_tube_id) REFERENCES hic_library(hic_library_tube_id);
ALTER TABLE public.sequencing ADD CONSTRAINT fk_illumina_library FOREIGN KEY (illumina_library_tube_id) REFERENCES illumina_library(illumina_library_tube_id);
ALTER TABLE public.sequencing ADD CONSTRAINT fk_ont_library FOREIGN KEY (ont_library_tube_id) REFERENCES ont_library(ont_library_tube_id);
ALTER TABLE public.sequencing ADD CONSTRAINT fk_pacbio_library FOREIGN KEY (pacbio_library_tube_id) REFERENCES pacbio_library(pacbio_library_tube_id);
ALTER TABLE public.species ADD CONSTRAINT "Species_pkey" PRIMARY KEY (species);
ALTER TABLE public.species_ncbi_assembly ADD CONSTRAINT species_ncbi_assembly_pkey PRIMARY KEY (assembly_accession);
ALTER TABLE public.species_ncbi_assembly ADD CONSTRAINT species_ncbi_assembly_species_fkey FOREIGN KEY (species) REFERENCES species(species);
ALTER TABLE public.tissue ADD CONSTRAINT "Tissue_pkey" PRIMARY KEY (tissue_id);
ALTER TABLE public.tissue ADD CONSTRAINT fk_og_id FOREIGN KEY (og_id) REFERENCES sample(og_id);
