ALTER TABLE public.blast_filtered_lca ADD CONSTRAINT blast_filtered_lca_pk PRIMARY KEY (og_id, tech, seq_date, code, annotation, match_sequence_id, region);
ALTER TABLE public.design_description ADD CONSTRAINT design_description_pk PRIMARY KEY (design_no);
ALTER TABLE public.dna_extraction ADD CONSTRAINT "DNA_Extraction_pkey" PRIMARY KEY (dna_id);
ALTER TABLE public.dna_extraction ADD CONSTRAINT fk_tissue_id FOREIGN KEY (tissue_id) REFERENCES tissue(tissue_id);
ALTER TABLE public.draft_genomes ADD CONSTRAINT draft_genomes_pkey PRIMARY KEY (og_id, seq_date);
ALTER TABLE public.hic_library ADD CONSTRAINT "HiC_Library_pkey" PRIMARY KEY (hic_library_tube_id);
ALTER TABLE public.hic_library ADD CONSTRAINT fk_lysate_id FOREIGN KEY (lysate_id) REFERENCES hic_lysate(lysate_id);
ALTER TABLE public.hic_lysate ADD CONSTRAINT "HiC_Lysate_pkey" PRIMARY KEY (lysate_id);
ALTER TABLE public.hic_lysate ADD CONSTRAINT fk_tissue_id FOREIGN KEY (tissue_id) REFERENCES tissue(tissue_id);
ALTER TABLE public.hic_reads_qc ADD CONSTRAINT hic_reads_qc_pkey PRIMARY KEY (og_id, tissue, ext_type, lib_code, lane, run_id);
ALTER TABLE public.hifi_reads_qc ADD CONSTRAINT hifi_reads_qc_pkey PRIMARY KEY (og_id, tissue, ext_type, lib_code, run_id);
ALTER TABLE public.illumina_library ADD CONSTRAINT "Illumina_Library_pkey" PRIMARY KEY (illumina_library_tube_id);
ALTER TABLE public.illumina_library ADD CONSTRAINT fk_dna_id FOREIGN KEY (dna_id) REFERENCES dna_extraction(dna_id);
ALTER TABLE public.lca ADD CONSTRAINT fk_mitogenome FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES mitogenome_data(og_id, tech, seq_date, code);
ALTER TABLE public.lca ADD CONSTRAINT lca_results_unique UNIQUE (og_id, tech, seq_date, code, annotation, region, lca_run_date);
ALTER TABLE public.lca_old ADD CONSTRAINT fk_mitogenome FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES mitogenome_data(og_id, tech, seq_date, code);
ALTER TABLE public.lca_old ADD CONSTRAINT lca_unique UNIQUE (og_id, tech, seq_date, code, annotation, region, lca_run_date);
ALTER TABLE public.lca_raw_results ADD CONSTRAINT fk_mitogenome FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES mitogenome_data(og_id, tech, seq_date, code);
ALTER TABLE public.lca_raw_results ADD CONSTRAINT lca_raw_results_unique UNIQUE (og_id, tech, seq_date, code, annotation, sequence_region, lca_run_date, accession_id);
ALTER TABLE public.lca_validation ADD CONSTRAINT lca_validation_mitogenome_data_fk FOREIGN KEY (og_id, tech, seq_date, code) REFERENCES mitogenome_data(og_id, tech, seq_date, code);
ALTER TABLE public.lca_validation ADD CONSTRAINT lca_validation_pk PRIMARY KEY (og_id, tech, seq_date, code, annotation);
ALTER TABLE public.master_species ADD CONSTRAINT master_species_pkey PRIMARY KEY (species);
ALTER TABLE public.mitogenome_data ADD CONSTRAINT mitogenome_data_pkey PRIMARY KEY (og_id, tech, seq_date, code);
ALTER TABLE public.mitogenome_data ADD CONSTRAINT mitogenome_data_unique UNIQUE (og_id, tech, seq_date, code, annotation);
ALTER TABLE public.ont_library ADD CONSTRAINT "ONT_Library_pkey" PRIMARY KEY (ont_library_tube_id);
ALTER TABLE public.ont_library ADD CONSTRAINT fk_dna_id FOREIGN KEY (dna_id) REFERENCES dna_extraction(dna_id);
ALTER TABLE public.pacbio_library ADD CONSTRAINT "PacBio_Library_pkey" PRIMARY KEY (pacbio_library_tube_id);
ALTER TABLE public.pacbio_library ADD CONSTRAINT fk_dna_id FOREIGN KEY (dna_id) REFERENCES dna_extraction(dna_id);
ALTER TABLE public.raw_data ADD CONSTRAINT raw_data_pkey PRIMARY KEY (run_id, lane_id, filename);
ALTER TABLE public.raw_qc ADD CONSTRAINT raw_qc_pkey PRIMARY KEY (og_id);
ALTER TABLE public.ref_genomes ADD CONSTRAINT ref_genomes_pkey PRIMARY KEY (og_id, seq_date, stage, haplotype, version);
ALTER TABLE public.ref_genomes_assembly_uploads ADD CONSTRAINT ref_genomes_uploads_pkey PRIMARY KEY (og_id);
ALTER TABLE public.ref_genomes_sra_uploads ADD CONSTRAINT ref_genomes_sra_runs_og_id_fkey FOREIGN KEY (og_id) REFERENCES ref_genomes_assembly_uploads(og_id);
ALTER TABLE public.ref_genomes_sra_uploads ADD CONSTRAINT ref_genomes_sra_runs_pkey PRIMARY KEY (srr_accession);
ALTER TABLE public.rna_extraction ADD CONSTRAINT "RNA_Extraction_pkey" PRIMARY KEY (rna_id);
ALTER TABLE public.rna_extraction ADD CONSTRAINT fk_tissue_id FOREIGN KEY (tissue_id) REFERENCES tissue(tissue_id);
ALTER TABLE public.rna_library_ilmn ADD CONSTRAINT "RNA_Library_pkey" PRIMARY KEY (rna_library_tube_id);
ALTER TABLE public.rna_library_ilmn ADD CONSTRAINT fk_rna_id FOREIGN KEY (rna_id) REFERENCES rna_extraction(rna_id);
ALTER TABLE public.rna_library_kinx ADD CONSTRAINT rna_library_kinx_pkey PRIMARY KEY (rna_library_tube_id);
ALTER TABLE public.rna_qc_kinnex ADD CONSTRAINT rna_qc_run_id_tube_uniq UNIQUE (run_id, rna_tube_id);
ALTER TABLE public.sample ADD CONSTRAINT "Sample_pkey" PRIMARY KEY (og_id);
ALTER TABLE public.sequencing ADD CONSTRAINT "Sequencing_pkey" PRIMARY KEY (sequencing_id);
ALTER TABLE public.sequencing ADD CONSTRAINT fk_hic_library FOREIGN KEY (hic_library_tube_id) REFERENCES hic_library(hic_library_tube_id);
ALTER TABLE public.sequencing ADD CONSTRAINT fk_illumina_library FOREIGN KEY (illumina_library_tube_id) REFERENCES illumina_library(illumina_library_tube_id);
ALTER TABLE public.sequencing ADD CONSTRAINT fk_ont_library FOREIGN KEY (ont_library_tube_id) REFERENCES ont_library(ont_library_tube_id);
ALTER TABLE public.sequencing ADD CONSTRAINT fk_pacbio_library FOREIGN KEY (pacbio_library_tube_id) REFERENCES pacbio_library(pacbio_library_tube_id);
ALTER TABLE public.species ADD CONSTRAINT "Species_pkey" PRIMARY KEY (species);
ALTER TABLE public.species_ncbi_assembly ADD CONSTRAINT species_ncbi_assembly_pkey PRIMARY KEY (assembly_accession);
ALTER TABLE public.species_ncbi_assembly ADD CONSTRAINT species_ncbi_assembly_species_fkey FOREIGN KEY (species) REFERENCES species(species);
ALTER TABLE public.tissue ADD CONSTRAINT "Tissue_pkey" PRIMARY KEY (tissue_id);
ALTER TABLE public.tissue ADD CONSTRAINT fk_og_id FOREIGN KEY (og_id) REFERENCES sample(og_id);
