CREATE UNIQUE INDEX blast_filtered_lca_new_pk ON public.blast_filtered_lca USING btree (og_id, tech, seq_date, code, annotation, match_sequence_id, region);
CREATE UNIQUE INDEX blast_filtered_lca_pk ON public."blast_filtered_lca_SS260818" USING btree (og_id, tech, seq_date, code, annotation, match_sequence_id, region);
CREATE UNIQUE INDEX data_package_artifact_delivery_id_component_id_artifact_typ_key ON public.data_package_artifact USING btree (delivery_id, component_id, artifact_type, batch_number, filename);
CREATE UNIQUE INDEX data_package_artifact_pkey ON public.data_package_artifact USING btree (id);
CREATE INDEX data_package_artifact_remote_idx ON public.data_package_artifact USING btree (remote_path);
CREATE UNIQUE INDEX data_package_component_delivery_id_component_type_key ON public.data_package_component USING btree (delivery_id, component_type);
CREATE UNIQUE INDEX data_package_component_pkey ON public.data_package_component USING btree (id);
CREATE UNIQUE INDEX data_package_delivery_pkey ON public.data_package_delivery USING btree (id);
CREATE UNIQUE INDEX data_package_delivery_project_id_delivery_version_key ON public.data_package_delivery USING btree (project_id, delivery_version);
CREATE INDEX data_package_delivery_project_status_idx ON public.data_package_delivery USING btree (project_id, status, created_at DESC);
CREATE UNIQUE INDEX data_package_delivery_run_id_key ON public.data_package_delivery USING btree (run_id);
CREATE UNIQUE INDEX data_package_email_pkey ON public.data_package_email USING btree (id);
CREATE UNIQUE INDEX data_package_email_preview_id_key ON public.data_package_email USING btree (preview_id);
CREATE UNIQUE INDEX data_package_email_recipient_email_id_recipient_role_email_key ON public.data_package_email_recipient USING btree (email_id, recipient_role, email);
CREATE UNIQUE INDEX data_package_email_recipient_pkey ON public.data_package_email_recipient USING btree (id);
CREATE UNIQUE INDEX data_package_item_component_id_og_id_seq_id_key ON public.data_package_item USING btree (component_id, og_id, seq_id);
CREATE INDEX data_package_item_og_idx ON public.data_package_item USING btree (og_id);
CREATE UNIQUE INDEX data_package_item_pkey ON public.data_package_item USING btree (id);
CREATE INDEX data_package_link_expiry_idx ON public.data_package_link_set USING btree (delivery_id, expires_at DESC);
CREATE UNIQUE INDEX data_package_link_set_pkey ON public.data_package_link_set USING btree (id);
CREATE UNIQUE INDEX design_description_pk ON public.design_description USING btree (design_no);
CREATE UNIQUE INDEX "DNA_Extraction_pkey" ON public.dna_extraction USING btree (dna_id);
CREATE INDEX idx_dna_extraction_og_id ON public.dna_extraction USING btree (og_id);
CREATE INDEX idx_dna_extraction_tissue_id ON public.dna_extraction USING btree (tissue_id);
CREATE UNIQUE INDEX draft_genomes_pkey ON public.draft_genomes USING btree (og_id, seq_date);
CREATE UNIQUE INDEX ena_related_assemblies_og_id_relationship_type_archive_acce_key ON public.ena_related_assemblies USING btree (og_id, relationship_type, archive, accession);
CREATE UNIQUE INDEX ena_related_assemblies_pkey ON public.ena_related_assemblies USING btree (id);
CREATE UNIQUE INDEX ena_related_one_primary_idx ON public.ena_related_assemblies USING btree (og_id, relationship_type) WHERE is_primary;
CREATE UNIQUE INDEX ena_specimen_accessions_ena_biosample_accession_key ON public.ena_specimen_accessions USING btree (ena_biosample_accession);
CREATE UNIQUE INDEX ena_specimen_accessions_og_numeric_key ON public.ena_specimen_accessions USING btree (og_numeric);
CREATE UNIQUE INDEX ena_specimen_accessions_pkey ON public.ena_specimen_accessions USING btree (og_id);
CREATE INDEX ena_submissions_identity_idx ON public.ena_submissions USING btree (og_id, tech, seq_date, code, annotation);
CREATE UNIQUE INDEX ena_submissions_pkey ON public.ena_submissions USING btree (full_seqid, webin_mode);
CREATE INDEX ena_submissions_status_idx ON public.ena_submissions USING btree (submission_status);
CREATE INDEX ena_validation_attempts_identity_idx ON public.ena_validation_attempts USING btree (og_id, tech, seq_date, code, annotation);
CREATE UNIQUE INDEX ena_validation_attempts_key_idx ON public.ena_validation_attempts USING btree (full_seqid, ena_study, validation_attempt);
CREATE UNIQUE INDEX ena_validation_attempts_pkey ON public.ena_validation_attempts USING btree (id);
CREATE INDEX ena_validation_attempts_recorded_at_idx ON public.ena_validation_attempts USING btree (recorded_at DESC);
CREATE UNIQUE INDEX "HiC_Library_pkey" ON public.hic_library USING btree (hic_library_tube_id);
CREATE INDEX idx_hic_library_lysate_id ON public.hic_library USING btree (lysate_id);
CREATE INDEX idx_hic_library_og_id ON public.hic_library USING btree (og_id);
CREATE UNIQUE INDEX "HiC_Lysate_pkey" ON public.hic_lysate USING btree (lysate_id);
CREATE INDEX idx_hic_lysate_tissue_id ON public.hic_lysate USING btree (tissue_id);
CREATE UNIQUE INDEX hic_reads_qc_pkey ON public.hic_reads_qc USING btree (og_id, tissue, ext_type, lib_code, lane, run_id);
CREATE UNIQUE INDEX hifi_reads_qc_pkey ON public.hifi_reads_qc USING btree (og_id, tissue, ext_type, lib_code, run_id);
CREATE UNIQUE INDEX "Illumina_Library_pkey" ON public.illumina_library USING btree (illumina_library_tube_id);
CREATE INDEX idx_illumina_library_dna_id ON public.illumina_library USING btree (dna_id);
CREATE INDEX idx_illumina_library_og_id ON public.illumina_library USING btree (og_id);
CREATE UNIQUE INDEX lca_content_unique ON public.lca USING btree (og_id, tech, seq_date, code, annotation, region, content_hash);
CREATE UNIQUE INDEX lca_results_unique ON public."lca_SS260818" USING btree (og_id, tech, seq_date, code, annotation, region, lca_run_date);
CREATE UNIQUE INDEX lca_unique ON public.lca_old USING btree (og_id, tech, seq_date, code, annotation, region, lca_run_date);
CREATE UNIQUE INDEX lca_raw_results_content_unique ON public.lca_raw_results USING btree (og_id, tech, seq_date, code, annotation, sequence_region, accession_id, content_hash);
CREATE UNIQUE INDEX lca_raw_results_unique ON public."lca_raw_results_SS260818" USING btree (og_id, tech, seq_date, code, annotation, sequence_region, lca_run_date, accession_id);
CREATE UNIQUE INDEX lca_validation_new_pk ON public.lca_validation USING btree (og_id, tech, seq_date, code, annotation);
CREATE UNIQUE INDEX lca_validation_pk ON public."lca_validation_SS260818" USING btree (og_id, tech, seq_date, code, annotation);
CREATE UNIQUE INDEX master_species_pkey ON public.master_species USING btree (species);
CREATE UNIQUE INDEX master_species_genome_pkey ON public.master_species_genome USING btree (species);
CREATE INDEX mitogenome_data_depth_method_idx_1 ON public.mitogenome_data USING btree (depth_method);
CREATE UNIQUE INDEX mitogenome_data_pkey_1 ON public.mitogenome_data USING btree (og_id, tech, seq_date, code);
CREATE UNIQUE INDEX mitogenome_data_unique_1 ON public.mitogenome_data USING btree (og_id, tech, seq_date, code, annotation);
CREATE INDEX mitogenome_data_depth_method_idx ON public."mitogenome_data_SS260818" USING btree (depth_method);
CREATE UNIQUE INDEX mitogenome_data_pkey ON public."mitogenome_data_SS260818" USING btree (og_id, tech, seq_date, code);
CREATE UNIQUE INDEX mitogenome_data_unique ON public."mitogenome_data_SS260818" USING btree (og_id, tech, seq_date, code, annotation);
CREATE UNIQUE INDEX ncbi_genome_assemblies_assembly_accession_key ON public.ncbi_genome_assemblies USING btree (assembly_accession);
CREATE UNIQUE INDEX "ONT_Library_pkey" ON public.ont_library USING btree (ont_library_tube_id);
CREATE INDEX idx_ont_library_dna_id ON public.ont_library USING btree (dna_id);
CREATE INDEX idx_ont_library_og_id ON public.ont_library USING btree (og_id);
CREATE UNIQUE INDEX "PacBio_Library_pkey" ON public.pacbio_library USING btree (pacbio_library_tube_id);
CREATE INDEX idx_pacbio_library_dna_id ON public.pacbio_library USING btree (dna_id);
CREATE INDEX idx_pacbio_library_og_id ON public.pacbio_library USING btree (og_id);
CREATE INDEX project_delivery_contact_active_idx ON public.project_delivery_contact USING btree (project_id, active);
CREATE UNIQUE INDEX project_delivery_contact_pkey ON public.project_delivery_contact USING btree (id);
CREATE UNIQUE INDEX project_delivery_contact_project_id_email_recipient_role_key ON public.project_delivery_contact USING btree (project_id, email, recipient_role);
CREATE UNIQUE INDEX raw_data_pkey ON public.raw_data USING btree (run_id, lane_id, filename);
CREATE UNIQUE INDEX raw_qc_og_id_uq ON public.raw_qc USING btree (og_id);
CREATE UNIQUE INDEX raw_qc_pkey ON public.raw_qc USING btree (og_id);
CREATE UNIQUE INDEX ref_genomes_pkey ON public.ref_genomes USING btree (og_id, seq_date, stage, haplotype, version);
CREATE UNIQUE INDEX ref_genomes_uploads_pkey ON public.ref_genomes_assembly_uploads USING btree (og_id);
CREATE INDEX idx_ref_genomes_sra_uploads_og_id ON public.ref_genomes_sra_uploads USING btree (og_id);
CREATE UNIQUE INDEX ref_genomes_sra_runs_pkey ON public.ref_genomes_sra_uploads USING btree (srr_accession);
CREATE UNIQUE INDEX "RNA_Extraction_pkey" ON public.rna_extraction USING btree (rna_id);
CREATE INDEX idx_rna_extraction_og_id ON public.rna_extraction USING btree (og_id);
CREATE INDEX idx_rna_extraction_tissue_id ON public.rna_extraction USING btree (tissue_id);
CREATE UNIQUE INDEX "RNA_Library_pkey" ON public.rna_library_ilmn USING btree (rna_library_tube_id);
CREATE INDEX idx_rna_library_ilmn_og_id ON public.rna_library_ilmn USING btree (og_id);
CREATE INDEX idx_rna_library_ilmn_rna_id ON public.rna_library_ilmn USING btree (rna_id);
CREATE INDEX idx_rna_library_kinx_og_id ON public.rna_library_kinx USING btree (og_id);
CREATE INDEX idx_rna_library_kinx_rna_id ON public.rna_library_kinx USING btree (rna_id);
CREATE UNIQUE INDEX rna_library_kinx_pkey ON public.rna_library_kinx USING btree (rna_library_tube_id);
CREATE UNIQUE INDEX rna_qc_run_id_tube_uniq ON public.rna_qc_kinnex USING btree (run_id, rna_tube_id);
CREATE UNIQUE INDEX "Sample_pkey" ON public.sample USING btree (og_id);
CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (filename);
CREATE UNIQUE INDEX "Sequencing_pkey" ON public.sequencing USING btree (sequencing_id);
CREATE INDEX idx_sequencing_hic_library_tube_id ON public.sequencing USING btree (hic_library_tube_id);
CREATE INDEX idx_sequencing_illumina_library_tube_id ON public.sequencing USING btree (illumina_library_tube_id);
CREATE INDEX idx_sequencing_og_id ON public.sequencing USING btree (og_id);
CREATE INDEX idx_sequencing_ont_library_tube_id ON public.sequencing USING btree (ont_library_tube_id);
CREATE INDEX idx_sequencing_pacbio_library_tube_id ON public.sequencing USING btree (pacbio_library_tube_id);
CREATE UNIQUE INDEX "Species_pkey" ON public.species USING btree (species);
CREATE UNIQUE INDEX species_ncbi_assembly_one_chosen_idx ON public.species_ncbi_assembly USING btree (species) WHERE is_chosen;
CREATE UNIQUE INDEX species_ncbi_assembly_pkey ON public.species_ncbi_assembly USING btree (assembly_accession);
CREATE INDEX species_ncbi_assembly_species_idx ON public.species_ncbi_assembly USING btree (species);
CREATE UNIQUE INDEX "Tissue_pkey" ON public.tissue USING btree (tissue_id);
CREATE INDEX idx_tissue_og_id ON public.tissue USING btree (og_id);
