CREATE UNIQUE INDEX blast_filtered_lca_pk ON public.blast_filtered_lca USING btree (og_id, tech, seq_date, code, annotation, match_sequence_id, region);
CREATE UNIQUE INDEX design_description_pk ON public.design_description USING btree (design_no);
CREATE UNIQUE INDEX "DNA_Extraction_pkey" ON public.dna_extraction USING btree (dna_id);
CREATE UNIQUE INDEX draft_genomes_pkey ON public.draft_genomes USING btree (og_id, seq_date);
CREATE UNIQUE INDEX "HiC_Library_pkey" ON public.hic_library USING btree (hic_library_tube_id);
CREATE UNIQUE INDEX "HiC_Lysate_pkey" ON public.hic_lysate USING btree (lysate_id);
CREATE UNIQUE INDEX hic_reads_qc_pkey ON public.hic_reads_qc USING btree (og_id, tissue, ext_type, lib_code, lane, run_id);
CREATE UNIQUE INDEX hifi_reads_qc_pkey ON public.hifi_reads_qc USING btree (og_id, tissue, ext_type, lib_code, run_id);
CREATE UNIQUE INDEX "Illumina_Library_pkey" ON public.illumina_library USING btree (illumina_library_tube_id);
CREATE UNIQUE INDEX lca_results_unique ON public.lca USING btree (og_id, tech, seq_date, code, annotation, region, lca_run_date);
CREATE UNIQUE INDEX lca_unique ON public.lca_old USING btree (og_id, tech, seq_date, code, annotation, region, lca_run_date);
CREATE UNIQUE INDEX lca_raw_results_unique ON public.lca_raw_results USING btree (og_id, tech, seq_date, code, annotation, sequence_region, lca_run_date, accession_id);
CREATE UNIQUE INDEX lca_validation_pk ON public.lca_validation USING btree (og_id, tech, seq_date, code, annotation);
CREATE UNIQUE INDEX master_species_pkey ON public.master_species USING btree (species);
CREATE UNIQUE INDEX mitogenome_data_pkey ON public.mitogenome_data USING btree (og_id, tech, seq_date, code);
CREATE UNIQUE INDEX mitogenome_data_unique ON public.mitogenome_data USING btree (og_id, tech, seq_date, code, annotation);
CREATE UNIQUE INDEX "ONT_Library_pkey" ON public.ont_library USING btree (ont_library_tube_id);
CREATE UNIQUE INDEX "PacBio_Library_pkey" ON public.pacbio_library USING btree (pacbio_library_tube_id);
CREATE UNIQUE INDEX raw_data_pkey ON public.raw_data USING btree (run_id, lane_id, filename);
CREATE UNIQUE INDEX raw_qc_og_id_uq ON public.raw_qc USING btree (og_id);
CREATE UNIQUE INDEX raw_qc_pkey ON public.raw_qc USING btree (og_id);
CREATE UNIQUE INDEX ref_genomes_pkey ON public.ref_genomes USING btree (og_id, seq_date, stage, haplotype, version);
CREATE UNIQUE INDEX ref_genomes_uploads_pkey ON public.ref_genomes_assembly_uploads USING btree (og_id);
CREATE UNIQUE INDEX ref_genomes_sra_runs_pkey ON public.ref_genomes_sra_uploads USING btree (srr_accession);
CREATE UNIQUE INDEX "RNA_Extraction_pkey" ON public.rna_extraction USING btree (rna_id);
CREATE UNIQUE INDEX "RNA_Library_pkey" ON public.rna_library_ilmn USING btree (rna_library_tube_id);
CREATE UNIQUE INDEX rna_library_kinx_pkey ON public.rna_library_kinx USING btree (rna_library_tube_id);
CREATE UNIQUE INDEX rna_qc_run_id_tube_uniq ON public.rna_qc_kinnex USING btree (run_id, rna_tube_id);
CREATE UNIQUE INDEX "Sample_pkey" ON public.sample USING btree (og_id);
CREATE UNIQUE INDEX "Sequencing_pkey" ON public.sequencing USING btree (sequencing_id);
CREATE UNIQUE INDEX "Species_pkey" ON public.species USING btree (species);
CREATE UNIQUE INDEX species_ncbi_assembly_one_chosen_idx ON public.species_ncbi_assembly USING btree (species) WHERE is_chosen;
CREATE UNIQUE INDEX species_ncbi_assembly_pkey ON public.species_ncbi_assembly USING btree (assembly_accession);
CREATE INDEX species_ncbi_assembly_species_idx ON public.species_ncbi_assembly USING btree (species);
CREATE UNIQUE INDEX "Tissue_pkey" ON public.tissue USING btree (tissue_id);
